markdown: rdiscount
pygments: true
permalink: :categories/:year/:month/:day/:title 
#permalink: :categories/:title 
title : 会飞de树's Code Blocks
author :
  name : 会飞de树
  email : wellwy@gmail.com
  github : wellwy
  twitter : 
  feedburner : 

baseurl : /original
homepage : /index.html
graphs : /original/include/graphs
static : http://wellwy.github.io/static

comments: true
googleAnalytics : true
